language: python
python:
- 2.7
before_install:
- echo "127.0.1.1 "`hostname` | sudo tee /etc/hosts
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
- bash Miniconda-latest-Linux-x86_64.sh -b -p $HOME/miniconda2 -f
- wget -O $HOME/autoseq-scripts.zip https://github.com/dakl/autoseq-scripts/archive/master.zip
- unzip -o $HOME/autoseq-scripts.zip -d $HOME

install:
- export PATH=$HOME/miniconda2/bin/:$HOME/autoseq-scripts-master/:$PATH
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda info -a
- conda config --add channels r
- conda config --add channels bioconda
- conda install --file conda-list.txt
- pip install -r requirements.txt
- pip install .
- mkdir -p $HOME/genome-zipped/
- mkdir $HOME/genome
- wget --no-clobber -O $HOME/genome-zipped/test-genome.tar.gz https://export.uppmax.uu.se/b2010040/test-genome.tar.gz
- tar xvfz $HOME/genome-zipped/test-genome.tar.gz -C $HOME
- wget --no-clobber -O $HOME/test-libraries.tar.gz https://export.uppmax.uu.se/b2010040/test-libraries.tar.gz
- tar xvfz $HOME/test-libraries.tar.gz -C $HOME

script: nosetests --nocapture
notifications:
  slack:
    secure: C9Ygg8L/ukxSTjS3BE+9mdAebGvUheYOQFeLoFl6TKhydK6/dgclRk3gP49BU+iR+GPr2uc8FPaGFK2cjQEo1FTbJKKVv7a8vla/0icfFBI/SqarDtGa95zqd8ixDpc3IEnmSiN+zEr6abdZit7DC0bsMOmtUAkgEJO6fPMQCpurAkoP9di6rtfnIIV2PWTQM07X3MMPbEC16iNx1JdaD/mX8OOoPPFkDQTRK5y//SyDwhscuEh8+zY3R+Va+JXAuW1nxzgJogEIxRvti1YDRjg8dM3KPB9pu7Bjs7jZH2aYJvLV8K+rHVmoV5N1votC/2otA5+jkxQf6cTtDtkkaVpZNBtS+uEPIW0PRJ8rUzMHE+BFBHGjsqhVY7PrgsM3/AE58HcYa3cmUYLvpmEs5YSZ0Zy+8nX+0PPWb3qp3NdRqvTnIJjd/p9des8nTt1K29DYoWwMjQSWjOQbaNrafNdFPRKmDC9EnTbuB4oGTN83qZJ74jBc6V+/t5I84nsEcI7yqnMW/YKSLdgTr+eGemJtDjg4vVTw0X9fm8+ZpH0yY7Plgl7lSKpEB1muVthBOjF58JvRAlsKxPFoJtPtBYMOV4AtON0TnSzpJ9mHkrQ8iIGETr/6H69ac3zqEZDGko5e/fbruIrl8TyXTZ7eZKEHl/2SG7m0n/yo3lreW8I=
