language: python

python:
  - 2.7

before_install:
  # Temporal fix for networking problem: https://github.com/travis-ci/travis-ci/issues/1484
  - echo "127.0.1.1 "`hostname` | sudo tee /etc/hosts
  # Get and install anaconda for custom Python installation
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  - bash Miniconda-latest-Linux-x86_64.sh -b -p $HOME/miniconda2 -f
  - wget -O $HOME/autoseq-scripts.zip https://github.com/dakl/autoseq-scripts/archive/master.zip
  - unzip -o $HOME/autoseq-scripts.zip -d $HOME

# command to install dependencies
install:
  - export PATH=$HOME/miniconda2/bin/:$HOME/autoseq-scripts-master/:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda config --add channels r
  - conda config --add channels bioconda
  - conda install --file conda-list.txt
  - pip install -r requirements.txt
  - pip install .

  # ref
  - mkdir -p $HOME/genome-zipped/
  - mkdir $HOME/genome
  - wget --no-clobber -O $HOME/genome-zipped/test-genome.tar.gz https://export.uppmax.uu.se/b2010040/test-genome.tar.gz
  - tar xvfz $HOME/genome-zipped/test-genome.tar.gz -C $HOME

  # test data
  - wget --no-clobber -O $HOME/test-libraries.tar.gz https://export.uppmax.uu.se/b2010040/test-libraries.tar.gz
  - tar xvfz $HOME/test-libraries.tar.gz -C $HOME

# command to run tests
script: nosetests --nocapture
